# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Windows
      run: dotnet publish -r win-x64 ./release/win ./BambuVideoStream
    - name: Publish Linux
      run: dotnet publish -r linux-x64 -o ./release/linux ./BambuVideoStream
    - name: Publish OSX-x64
      run: dotnet publish -r osx-x64 -o ./release/osx-x64 ./BambuVideoStream
    - name: Publish OSX-ARM
      run: dotnet publish -r osx-arm64 -o ./release/osx-arm64 ./BambuVideoStream
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: ./release
